### PR TITLE
chainlit and chat improvements

### PR DESCRIPTION
**Pull request by XThomasBU**
Feature additions and improvements in chainlit convo flow:

* Adding feature to change chat settings on the fly (chat_model, retriever, memory_window, view_sources)

WIP

Screenshot 2024-06-27 at 2 53 39 PM

### CODE REVIEW

**Comment by XThomasBU** [comment]
Refactored code in code/modules/chat

**Comment by trgardos** [comment]
To take this PR out of draft, remove auto logging and just use manual logging. Document how that is done. Agentic arch changes should be in a new PR.

**Comment by XThomasBU** [comment]
> To take this PR out of draft, remove auto logging and just use manual logging. Document how that is done. Agentic arch changes should be in a new PR.

@trgardos @Farid-Karimli 

Went back to auto logging, the previous code did not have the support to create multiple threads, and to continue conversations in different threads. Will need to code a workaround for 1) logging=False, 2) User Not Authenticated - Or -continue as guest

The logging  is handled by the `ChainlitDataLayer` - https://github.com/DL4DS/dl4ds_tutor/blob/chainlit_enhancements/code/modules/chat_processor/literal_ai.py - we could update its methods

**Comment by XThomasBU** [comment]
PR updates:

- Google OAuth
- Chat logging to literal ai for every authenticated user
- Changing LLM settings on the fly
- Displaying Follow up questions after LLM response
- Continue/Delete Previous Threads

**Comment by XThomasBU** [comment]
Will fix the conflicts, and request for review - would need end-to-end testing of both vectorstore creation and chat

**Review by trgardos — CHANGES_REQUESTED** [review]
When you update the LLM config in the UI to, say add follow up questions, when you create a new thread, the UI is all reset but it still produces follow up questions.

If it's an easy fix, change here. If it is a harder one, let's file as a bug and fix in a new PR.

**Comment by XThomasBU** [comment]
> When you update the LLM config in the UI to, say add follow up questions, when you create a new thread, the UI is all reset but it still produces follow up questions.
> 
> If it's an easy fix, change here. If it is a harder one, let's file as a bug and fix in a new PR.

Updated the code, when user creates a new chat/resumes a chat -- the settings are reset to default. An improvement to this is to set the settings from the last step of the thread

**Comment by trgardos** [comment]
> > When you update the LLM config in the UI to, say add follow up questions, when you create a new thread, the UI is all reset but it still produces follow up questions.
> > If it's an easy fix, change here. If it is a harder one, let's file as a bug and fix in a new PR.
> 
> Updated the code, when user creates a new chat/resumes a chat -- the settings are reset to default. An improvement to this is to set the settings from the last step of the thread

Want to create a feature request in Issues? @XThomasBU

**Review by trgardos — APPROVED** [review]

**Comment by XThomasBU** [comment]
Will try testing out the data loaders a bit more, and the new indexes created from those,  before merging to dev_branch

**Comment by trgardos** [comment]
@Farid-Karimli -- Please make sure that all the changes from your #45 are reflected in this PR now. Thx.

**Comment by XThomasBU** [comment]
Ready to merge - will make minor tweaks (if any) as separate smaller PRs

**Pull request merged**
