### PR TITLE
Code restructure

### PR DESCRIPTION
**Pull request by XThomasBU**
* updated code structure - same components but different file structure -- making it easier to maintain and add new components
* added literalai logging

### TODO:
* better method to handle prompts in -https://github.com/DL4DS/dl4ds_tutor/blob/58bee72f752e9608abb1dab76cb01ad64d6cf1c6/code/modules/chat/llm_tutor.py#L28
* better way to check for 'informativeness' of docs - https://github.com/DL4DS/dl4ds_tutor/blob/d9b873baf90d83a957866105b7c90919a55e66c6/code/modules/dataloader/data_loader.py#L226
* Need a better PDF parser - the current implementation does not handle images and equations, and it encodes special characters by their Unicode equivalents (e.g., \u2013 instead of '-')."

### CODE REVIEW

**Comment by trgardos** [comment]
@XThomasBU  -- what else do you plan to do before removing draft status of the PR?

**Comment by XThomasBU** [comment]
> @XThomasBU -- what else do you plan to do before removing draft status of the PR?

Ready for review now

**Comment by XThomasBU** [comment]
> @XThomasBU -- what else do you plan to do before removing draft status of the PR?

Made some final improvements, ready to review now

**Comment by XThomasBU** [comment]
More changes:
- Updated Chainlit and literalai, earlier version had bugs in fetching logs from literal
- Added an implementation to do TruLens eval from the logs obtained from literal

**Review by trgardos — COMMENTED** [review]
Some initial comments. Will post more as I continue my review.

**Review by trgardos — APPROVED** [review]

**Pull request merged**
