### PR TITLE
O auth implement

### PR DESCRIPTION
**Pull request by hemantsingh11**
Initial implementation of Google OAuth.

Also initial implementation of chat history storing using the literal.ai as demonstrated in the chainlit documentation (https://github.com/Chainlit/cookbook/tree/main/resume-chat). The chat history is attempted to be stored at cloud.getliteral.ai. Tom and Hemant signed in with Google BU accounts. For some reason the history doesn't show up yet.

### CODE REVIEW

**Comment by trgardos** [comment]
Will remove temporary files and Firebase references and make a PR.

**Comment by Farid-Karimli** [comment]
Tried this locally. Logging and logging out works, and chats get saved and associated with the user. They also get logged to LiteralAI with the user's email. Only thing is that the authentication only works on a Chromium browser. 

To get the authentication working, you need to set up OAuth 2.0 on Google Cloud ([credentials](https://console.cloud.google.com/apis/credentials)) and set up the env variables as described in the cookbook referenced in the first comment on this PR.

**Comment by XThomasBU** [comment]
> Tried this locally. Logging in and logging out works, and chats get saved and associated with the user. They also get logged to LiteralAI with the user's email. Only thing is that the authentication only works on a Chromium browser. It was working on Firefox, then stopped, not sure what happened, getting "Something went wrong" with no more info.
> 
> To get the authentication working, you need to set up OAuth 2.0 on Google Cloud ([credentials](https://console.cloud.google.com/apis/credentials)) and set up the env variables as described in the cookbook referenced in the first comment on this PR.

How is it getting logged to literalAI? Does chainlit handle that, if we pass in the literal_ai_key?

**Comment by Farid-Karimli** [comment]
> > Tried this locally. Logging in and logging out works, and chats get saved and associated with the user. They also get logged to LiteralAI with the user's email. Only thing is that the authentication only works on a Chromium browser. It was working on Firefox, then stopped, not sure what happened, getting "Something went wrong" with no more info.
> > To get the authentication working, you need to set up OAuth 2.0 on Google Cloud ([credentials](https://console.cloud.google.com/apis/credentials)) and set up the env variables as described in the cookbook referenced in the first comment on this PR.
> 
> How is it getting logged to literalAI? Does chainlit handle that, if we pass in the literal_ai_key?

Yes - [see here](https://docs.getliteral.ai/integrations/chainlit)

**Comment by trgardos** [comment]
Great! @Farid-Karimli  or @xavierohan -- Is all that is needed is to resolve the merge conflicts then? Will it support running without authentication but not retrieving chat history?

**Comment by Farid-Karimli** [comment]
It doesn't allow not authenticating, opening the application immediately redirects to Google's Authentication page.

**Comment by trgardos** [comment]
Redundant with #36. We can close this.

**Pull request closed without merging**
