### PR TITLE
Remove TinyLlama from LFS and add caching mechanism

### PR DESCRIPTION
**Pull request by ethanc-ec**
Utilizes Hugging Face's ```huggingface_hub``` python package to cache the local llm model (TinyLlama in this case). The `repo_id` and `filename` are hard coded due to the `repo_id` not being a 1 to 1 match with anything we currently have.

### CODE REVIEW

**Comment by XThomasBU** [comment]
Thanks! Could you update the code so that the `repo_id` and `file_name` is read from `config.yml`, under maybe `local_llm_params`

**Comment by trgardos** [comment]
Issue #38, SCRUM-77.

**Comment by XThomasBU** [comment]
Also @ethanc-ec, could you make your changes from the `dev_branch` and make a PR to `dev_branch`. We are using this to consolidate our changes and for testing, and once a stable build is made push it into `main`

Will need to add this to the README

**Comment by ethanc-ec** [comment]
> Thanks! Could you update the code so that the `repo_id` and `file_name` is read from `config.yml`, under maybe `local_llm_params`

Updated


> Also @ethanc-ec, could you make your changes from the `dev_branch` and make a PR to `dev_branch`. We are using this to consolidate our changes and for testing, and once a stable build is made push it into `main`

PR target branch changed to `dev_branch`

**Review by trgardos — APPROVED** [review]

**Pull request merged**
